# Generated by Django 2.0.7 on 2020-03-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khipu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=100, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='app_url',
            field=models.URLField(blank=True, null=True, verbose_name='App URL'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='attachment_urls',
            field=models.TextField(blank=True, null=True, verbose_name='URL archivos adjuntos al pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank nombre'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Bank ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancel_url',
            field=models.URLField(blank=True, null=True, verbose_name='Cancel URL'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='conciliation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concilation date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract_url',
            field=models.URLField(blank=True, null=True, verbose_name='Contract URL'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(max_length=20, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='custom',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Custom'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expires_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fixed_payer_personal_identifier',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Identificador personal'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='integrator_fee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comision integrador'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notification_token',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Token verificacion Khipu'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notify_api_version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='API Version notify'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notify_url',
            field=models.URLField(blank=True, null=True, verbose_name='Notify URL'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='out_of_date_conciliation',
            field=models.BooleanField(default=False, verbose_name='Pago fuera de la expiracion'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Payer email'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Payer name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=200, verbose_name='ID de la compra'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('regular_transfer', 'Transferencia normal'), ('simplified_transfer', 'Transferencia simplificada'), ('not_available', 'Para un pago marcado como realizado por otro medio por el cobrador')], max_length=50, null=True, verbose_name='Status payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Payment URL'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='personal_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificador personal pagador'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='picture_url',
            field=models.URLField(blank=True, null=True, verbose_name='Picture URL'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ready_for_terminal',
            field=models.BooleanField(default=False, verbose_name='Ready for terminal'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL comprobante'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receiver_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Receiver ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='responsible_user_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable del pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='return_url',
            field=models.URLField(blank=True, null=True, verbose_name='Return URL'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Send email'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='send_reminders',
            field=models.BooleanField(default=False, verbose_name='Reminders'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='simplified_transfer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Simplified URL'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pagador aún no paga'), ('veryfing', 'Se está verificando el pago'), ('done', 'El pago ya está confirmado'), ('amount_error', 'El pago tiene un monto que no es válido'), ('receiver_error', 'El pago tiene un receiver_id que no es válido')], max_length=50, null=True, verbose_name='Status payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_detail',
            field=models.CharField(blank=True, choices=[('pending', 'El pagador aún no comienza a pagar'), ('normal', 'El pago fue verificado y cancelado por algún medio de pago estandar'), ('marked-paid-by-payer', 'El pagador declaró que no pagará'), ('marked-as-abuse', 'El pagador declaró que no pagará y que el cobro fue no solicitado'), ('reversed', 'El pago fue anulado por el comercio, dinero fue devuelto al pagador')], max_length=50, null=True, verbose_name='Status payments detail'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subject',
            field=models.CharField(max_length=500, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transfer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Transfer URL'),
        ),
    ]
