# Generated by Django 2.0.7 on 2020-03-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khipu', '0002_auto_20200303_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='webpay_url',
            field=models.URLField(blank=True, null=True, verbose_name='Weboay URL'),
        ),
    ]
