# Generated by Django 2.0.7 on 2020-03-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khipu', '0003_payment_webpay_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='webpay_url',
            field=models.URLField(blank=True, null=True, verbose_name='Webpay URL'),
        ),
    ]
